# -*- coding: utf-8 -*-
"""despliegue_videojuegos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j2X2oaCpYG8yaYW19InucmVzlPcPi7Dg

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle

filename = 'modelo-tree-regressor (1).pkl'
modelo, min_max_scaler, variables = pickle.load(open(filename, 'rb'))
modelo

#Cargamos los datos futuros
#data = pd.read_csv("videojuegos-datosFuturos.csv")
#data.head()

#Despues de evaluar que el ipynb funciona cambiamos la fuente de datos

"""Despues de evaluar ya agregamos esta celda para crear la GUI"""

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de inversión en una tienda de videojuegos')

Edad = st.slider('Edad', min_value=14, max_value=52, value=20, step=1)

videojuego = st.selectbox('Videojuego', ["'Mass Effect'","'Battlefield'", "'Fifa'","'KOA: Reckoning'","'Crysis'","'Sim City'","'Dead Space'","'F1'"])

Plataforma = st.selectbox('Plataforma', ["'Play Station'", "'Xbox'","PC","Otros"])

Sexo = st.selectbox('Sexo', ['Hombre', 'Mujer'])

Consumidor_habitual = st.selectbox('Consumidor_habitual', ['True', 'False'])

#Dataframe

datos = [[Edad, videojuego,Plataforma,Sexo,Consumidor_habitual]]

data = pd.DataFrame(datos, columns=['Edad', 'videojuego','Plataforma','Sexo','Consumidor_habitual']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma','Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

# Los datos de entrenamiento y despligue deben ser identicos

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

'''Esto es para cuando se necesita normalizar:

#Se normaliza la edad para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
data_preparada.head()'''

# Predicciones
#Hacemos la predicción con el Tree
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

# Creando la tabla de caracteristicas + prediccion
data['Prediccion']=Y_pred
data.head()

# Prediccion final
data

# Mostrar la metrica del modelo

st.warning('El modelo tiene un error del 8 %')